### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by aDrIaNo34500** [hora-search/hora#16]
Hi

**Comment by salamer** [comment]
Hi, what can I do for you?

**Comment by AloNeAkasha** [comment]
I'm trying to learn how to code, so far I'm self taught and I happened to
find some government docs and i am fairly curious about them.  Can I get
some guidance?

**Comment by AloNeAkasha** [comment]
Hell0

**Comment by Maxen1711993** [comment]
Hi

**Comment by Maxen1711993** [comment]
> Hell0

Hello

**Comment by Maxen1711993** [comment]
> Hi

Hi sweet

**Comment by Maxen1711993** [comment]
> Hi, what can I do for you?

Anything

**Comment by AloNeAkasha** [comment]
Well I'm still trying to figure things out. I found an xml file yesterday that says it had no style information but there's a tree document. Can you tell me a little about it?

**Comment by Maxen1711993** [comment]
AmmHmm
