### ISSUE TITLE
Support for UTF-8 languages?

### ISSUE THREAD

**Issue by Hadryan** [hora-search/hora#21]
Any support for Arabic, Hebrew, Persian (Farsi), Chinese and other non-ascii languages would be great.

**Comment by Petergago-max** [comment]
Open

**Comment by salamer** [comment]
Do you mean the node index? node index currently is a [trait](https://github.com/hora-search/hora/blob/main/src/core/node.rs#L44)  that can be int or string, and string in rust support UTF-8
